server:
  port: 8030
## 数据库 配置数据源
spring:
  datasource:
    name: cksmaster
    url: jdbc:mysql://127.0.0.1:3306/cksmaster
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

# Dubbo 服务消费者配置
  dubbo:
    application:
      name: user

    registry:
      protocol: zookeeper
      address: localhost:2181

    protocol:
      name: dubbo
      port: 22881
      host: localhost

    scan: com.cksmaster.user.dubbo

#    mybatis:
#      mapperLocations: classpath:/mapper/*.xml
#      typeAliasesPackage: com.cksmaster.user.mapper

#    application:
#      name: user-consumer
#    registry:
#      protocol: zookeeper
#      address: localhost:2181,192.168.16.170:2181
#    protocol:
#      name: dubbo
#      port: 20880
#      host: localhost
#    scan: com.cksmaster.controller