server:
  port: 8010
  context-path: /common
## 数据库 配置数据源
spring:
  datasource:
    name: cks_master
    url: jdbc:mysql://192.168.15.38:3306/cksmaster?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

    # Dubbo 服务消费者配置
#  dubbo:
#    application:
#      name: common
#
#    registry:
#      protocol: zookeeper
#      address: localhost:2181
#
#    protocol:
#      name: dubbo
#      port: 21880
#      host: localhost
#
#    scan: com.cksmaster.common.dubbo

#    application:
#      name: user-consumer
#    registry:
#      protocol: zookeeper
#      address: localhost:2181,192.168.16.170:2181
#    protocol:
#      name: dubbo
#      port: 20880
#      host: localhost
#    scan: com.cksmaster.controller